coverage:
  status:
    project:
      default:
        target: 59%
        threshold: 1%
    patch:
      default:
        target: 70%

ignore:
  - "src/proto.rs"
  - "target/"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  show_carryforward_flags: true
  after_n_builds: 1

github_checks:
  annotations: true