version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: azolla_postgres_dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=azolla
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d azolla"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data: 