# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shepherd.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'shepherd.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshepherd.proto\x12\x0f\x61zolla.shepherd\x1a\x0c\x63ommon.proto\"Q\n\x13ReportResultRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12)\n\x06result\x18\x02 \x01(\x0b\x32\x19.azolla.common.TaskResult\"8\n\x14ReportResultResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2e\n\x06Worker\x12[\n\x0cReportResult\x12$.azolla.shepherd.ReportResultRequest\x1a%.azolla.shepherd.ReportResultResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shepherd_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REPORTRESULTREQUEST']._serialized_start=49
  _globals['_REPORTRESULTREQUEST']._serialized_end=130
  _globals['_REPORTRESULTRESPONSE']._serialized_start=132
  _globals['_REPORTRESULTRESPONSE']._serialized_end=188
  _globals['_WORKER']._serialized_start=190
  _globals['_WORKER']._serialized_end=291
# @@protoc_insertion_point(module_scope)
