use azolla_client::{azolla_task, Client, FromJsonValue, Task, TaskError, TaskResult, Worker};
use serde_json::{json, Value};

// Define a simple task using the proc macro
#[azolla_task]
async fn add_numbers(a: i32, b: i32) -> Result<Value, TaskError> {
    let sum = a + b;
    Ok(json!({
        "inputs": [a, b],
        "sum": sum
    }))
}

#[azolla_task]
async fn greet_user(name: String, age: Option<u32>) -> Result<Value, TaskError> {
    let greeting = match age {
        Some(age) => format!("Hello {name}, you are {age} years old!"),
        None => format!("Hello {name}!"),
    };

    Ok(json!({
        "greeting": greeting,
        "name": name,
        "age": age
    }))
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("🚀 Azolla Client Library Example");

    // This example shows how to use the azolla-client library
    // In a real application, you would connect to a running Azolla orchestrator

    // Create a client (this would normally connect to the orchestrator)
    println!("📡 Creating client...");
    let _client = match Client::builder()
        .endpoint("http://localhost:52710")
        .domain("example-domain")
        .build()
        .await
    {
        Ok(client) => client,
        Err(e) => {
            println!("⚠️  Could not connect to orchestrator: {}", e);
            println!("💡 This is expected if no orchestrator is running");
            println!("   The client library is properly configured though!");
            return Ok(());
        }
    };

    println!("✅ Client created successfully");

    // Create a worker (this would normally register with the orchestrator)
    println!("🔧 Creating worker with tasks...");
    let worker = Worker::builder()
        .orchestrator("localhost:52710")
        .domain("example-domain")
        .register_task(AddNumbersTask) // Generated by proc macro
        .register_task(GreetUserTask) // Generated by proc macro
        .build()
        .await?;

    println!("✅ Worker created with {} tasks", worker.task_count());
    println!("📝 Registered tasks:");
    println!("   - add_numbers (generated: AddNumbersTask)");
    println!("   - greet_user (generated: GreetUserTask)");

    // Show how task submission would work
    println!("\n📤 Example task submission (would fail without running orchestrator):");
    println!("   client.submit_task(\"add_numbers\").args((10, 20))?.submit().await?");
    println!("   client.submit_task(\"greet_user\").args((\"Alice\".to_string(), Some(25u32)))?.submit().await?");

    println!("\n🎉 Example completed successfully!");
    println!("💡 To use this in production:");
    println!("   1. Start an Azolla orchestrator");
    println!("   2. Update the endpoint to point to your orchestrator");
    println!("   3. Submit tasks and run workers as shown");

    Ok(())
}
