# Example basic configuration for the Azolla Orchestrator.
# Override values via AZOLLA__* environment variables for other environments.

[server]
port = 52710
 
[database]
url = "postgres://postgres:postgres@127.0.0.1:5432/azolla"

[event_stream]
max_batch_size = 100
adaptive_threshold = 10
max_wait_time_ms = 1
channel_capacity = 1000 

[domains]
default_concurrency_limit = 100

[domains.specific]
