{{- if .Values.benchmarkClient.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azolla-benchmark.benchmarkServiceAccountName" . }}
  labels:
    {{- include "azolla-benchmark.labels" . | nindent 4 }}
    app.kubernetes.io/component: benchmark-client
{{- end }}
