apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "azolla-benchmark.fullname" . }}-orchestrator
  labels:
    {{- include "azolla-benchmark.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "azolla-benchmark.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: orchestrator
  template:
    metadata:
      labels:
        {{- include "azolla-benchmark.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: orchestrator
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: orchestrator
          image: "{{ .Values.orchestrator.image.repository }}:{{ .Values.orchestrator.image.tag }}"
          imagePullPolicy: {{ .Values.orchestrator.image.pullPolicy }}
          env:
            - name: AZOLLA__SERVER__PORT
              value: "{{ .Values.orchestrator.service.port }}"
            {{- if .Values.database.existingSecret }}
            - name: AZOLLA__DATABASE__URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret | quote }}
                  key: {{ required "database.existingSecretKey must be provided when database.existingSecret is set" .Values.database.existingSecretKey }}
            {{- else if .Values.database.url }}
            - name: AZOLLA__DATABASE__URL
              value: {{ .Values.database.url | quote }}
            {{- else }}
            {{- fail "Either database.existingSecret or database.url must be provided" }}
            {{- end }}
            - name: RUST_LOG
              value: info
          ports:
            - name: grpc
              containerPort: {{ .Values.orchestrator.service.port }}
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 15
            periodSeconds: 10
          {{- with .Values.orchestrator.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.orchestrator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.orchestrator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.orchestrator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
