use anyhow::Result;
use config::{Config, ConfigError, Environment, File};
use deadpool_postgres::{Manager, Pool};
use serde::Deserialize;
use tokio_postgres::NoTls;
use openssl::ssl::{SslConnector, SslMethod, SslVerifyMode};
use postgres_openssl::MakeTlsConnector;

// Embed the migrations module generated by refinery
mod migrations {
    refinery::embed_migrations!();
}

#[derive(Debug, Deserialize, Clone)]
pub struct Database {
    pub url: String,
}

#[derive(Debug, Deserialize, Clone)]
pub struct Server {
    pub port: u16,
}

#[derive(Debug, Deserialize, Clone)]
pub struct Settings {
    pub database: Database,
    pub server: Server,
}

impl Settings {
    pub fn new() -> Result<Self, ConfigError> {
        let s = Config::builder()
            .add_source(File::with_name("config/default").required(false))
            .add_source(Environment::with_prefix("AZOLLA").separator("__"))
            .build()?;
        s.try_deserialize()
    }
}

pub type PgPool = deadpool_postgres::Pool;

pub fn create_pool(settings: &Settings) -> Result<PgPool> {
    let pg_config = settings.database.url.parse::<tokio_postgres::Config>()?;

    // Check if SSL is disabled in the connection string
    if pg_config.get_ssl_mode() == tokio_postgres::config::SslMode::Disable {
        let manager = Manager::new(pg_config, NoTls);
        let pool = Pool::builder(manager).build()?;
        Ok(pool)
    } else {
        let mut builder = SslConnector::builder(SslMethod::tls())?;
        // Accept self-signed certs (tests only!)
        builder.set_verify(SslVerifyMode::NONE);
        let connector = MakeTlsConnector::new(builder.build());

        let manager = Manager::new(pg_config, connector);
        let pool = Pool::builder(manager).build()?;
        Ok(pool)
    }
}

pub async fn run_migrations(pool: &PgPool) -> Result<()> {
    log::info!("Running database migrations...");
    let mut client = pool.get().await?;
    migrations::migrations::runner()
        .run_async(&mut **client)
        .await?;
    log::info!("Database migrations completed.");
    Ok(())
} 