use anyhow::Result;
use config::{Config, ConfigError, Environment, File};
use deadpool_postgres::{Manager, Pool};
use serde::Deserialize;
use tokio_postgres::NoTls;

// Embed the migrations module generated by refinery
mod migrations {
    refinery::embed_migrations!();
}

#[derive(Debug, Deserialize, Clone)]
pub struct Database {
    pub url: String,
}

#[derive(Debug, Deserialize, Clone)]
pub struct Server {
    pub port: u16,
}

#[derive(Debug, Deserialize, Clone)]
pub struct Settings {
    pub database: Database,
    pub server: Server,
}

impl Settings {
    pub fn new() -> Result<Self, ConfigError> {
        let s = Config::builder()
            .add_source(File::with_name("config/default").required(false))
            .add_source(Environment::with_prefix("AZOLLA").separator("__"))
            .build()?;
        s.try_deserialize()
    }
}

pub type PgPool = deadpool_postgres::Pool;

pub fn create_pool(settings: &Settings) -> Result<PgPool> {
    let pg_config = settings.database.url.parse::<tokio_postgres::Config>()?;
    let manager = Manager::new(pg_config, NoTls);
    let pool = Pool::builder(manager).build()?;
    Ok(pool)
}

pub async fn run_migrations(pool: &PgPool) -> Result<()> {
    let mut client = pool.get().await?;
    log::info!("Running database migrations...");
    migrations::migrations::runner()
        .run_async(&mut **client)
        .await?;
    log::info!("Database migrations completed.");
    Ok(())
} 