name: Lint

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    uses: ./.github/workflows/rust-setup.yml@main
    with:
      rust-toolchain-channel: stable
      rust-toolchain-components: rustfmt
      - name: Check formatting
        run: cargo fmt --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    uses: ./.github/workflows/rust-setup.yml@main
    with:
      rust-toolchain-channel: stable
      rust-toolchain-components: clippy
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings