name: Rust
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  simple-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run a simple command
      run: echo "Workflow triggered successfully!"